name: ai_tutor_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Core Dependencies for AI Tutor App
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  http: ^1.2.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  crypto: ^3.0.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0
  
  # Code generation dependencies
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # Pin analyzer version to avoid type parameter serialization bug
  analyzer: 6.2.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/